# Name of the feeder
name: LeakFeeder
# Leaks Folder to parse and send to AIL
leaks_folder: Leaks_Folder
# Output Folder of unprocessed split files
out_folder: Unprocessed_Leaks
# Output Folder of file that cannot be processed.
unprocessed_folder: Unprocessed_files
# Chunks size of split files
chunks: 100000
# API key for AIL authentication
api_key: XBAfnLEIM5jfgYfWqYN59njVtXPE-JF18CkxuWthhfFKQ49xFztXKJQ
# AIL API URL
ail_url: https://172.16.15.4:7000/api/v1
# Uniq identifier of the feeder
uuid: 17450648-9581-42a6-b7c4-28c13f4664bf
# Time sleep between API calls in seconds
wait: 1
